Add support to Rails 7 syntax
rafasoares/human_enum pull request #21
Opened 2024-03-25 02:25 UTC by guilhermearaujo

This fixes #20

2024-03-26 12:32 UTC, rafasoares commented
Hi @guilhermearaujo, thanks a lot for the PR!

Just a correction: 
`human_enum_value` and `self.human_enum_value` are exposed as convenience methods, so developers can fetch translated values without needing to set the property in the model instance.

2024-03-27 12:19 UTC, rafasoares requested changes

2024-03-28 08:50 UTC, rafasoares commented
> > Hi @guilhermearaujo, thanks a lot for the PR!
> 
> > 
> 
> > Just a correction: `human_enum_value` and `self.human_enum_value` are exposed as convenience methods, so developers can fetch translated values without needing to set the property in the model instance.
> 
> 
> 
> Ok, I can undo that, no problem.
> 
> 
> 
> I'm not sure if I understood the use case for them. Tell me if this is correct:
> 
> `MyClass` has `my_enum`, and you would like to get the text for `:enum_value`, so, without any instance, you can call `MyClass.human_enum_value(:my_enum, :enum_value)`
> 
> Or if you have an instance, you could call `my_instance.human_enum_value(:my_enum, :enum_value)`
> 
> 
> 
> Is that what you mean? If so, one could easily also call `MyClass.human_my_enums[:enum_value]`

You're probably correct. It's been so long since the initial design of the gem that I don't really remember lol. 

Given my other comment, though, I think it's  still necessary to have this as a method in the module. Maybe we can follow the rails approach of prefixing the method with `_`?

What do you think about `_humanize_enum`? That way it's clear what its purpose is and that it's not part of the public API.

2024-03-29 14:26 UTC, guilhermearaujo commented on lib/human_enum.rb
> +      humanize = lambda do |name, value, scope, ancestors|
Fixed by turning it into an anonymoys function

2024-04-27 22:15 UTC, guilhermearaujo commented
@rafasoares is there anything else I could change?

2024-04-29 10:25 UTC, rafasoares commented
Sorry @guilhermearaujo, I haven't had the time to properly review the new code. I'll do it in the next few days, promise :)

2024-09-04 13:22 UTC, rafasoares commented
Superseded by #29

2024-09-04 13:22 UTC, closed without merging